import type { Metadata } from "next";
import LoginFooter from "src/app/_components/loginfooter";
import { TRPCReactProvider } from "src/trpc/react"; 
import "src/styles/login.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';


export const metadata: Metadata = {
  title: "Rolec - Knowledge Base",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/r.svg" }],
};


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
        <html lang="en" >
          <meta name="viewport"/>
          <body className="flex flex-col items-center ">
                {<TRPCReactProvider>{children}</TRPCReactProvider>}
          </body>
        </html>
    </ClerkProvider>
  );
}