import type { Metadata } from "next";
import LoginFooter from "src/app/_components/loginfooter";
import { TRPCReactProvider } from "src/trpc/react"; 
import "src/styles/login.css"



export const metadata: Metadata = {
  title: "Rolec - Knowledge Base",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/r.svg" }],
};


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" >
      <meta name="viewport"/>
      <body className="flex flex-col items-center ">
        <div className="border rounded-3xl w-lg grid bg-[#F6F6F6] mt-3 ">
            {<TRPCReactProvider>{children}</TRPCReactProvider>}
            <LoginFooter label="Don't have an account?" link="Sign Up"></LoginFooter>
        </div>
      </body>
    </html>
  );
}