import "src/styles/globals.css";

import { type Metadata } from "next";
import NavBar from "../../_components/navbar";
import Footer from "../../_components/footer";
import CustomSeparator from "src/app/_components/breadcrumb-trail";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata: Metadata = {
  title: "Rolec - Knowledge Base",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/r.svg" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
      <div key= "dashboard-layout">
          <div className=" flex items-center bg-white w-full lg:pl-40 m-0 py-2 lg:py-0 lg:h-20">
            <div className="w-full"> 
              <NavBar/>
            </div>
          </div> 
          <div className="my-2 lg:mx-42 lg:my-5 mx-5 flex justify-between">
              <CustomSeparator></CustomSeparator>
          </div>
          {children}
          <SpeedInsights />
          <footer className="bg-[#262626] mt-5">
            <Footer>hello</Footer>
          </footer>
        </div>
  );
}
