import "src/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import {Montserrat} from "next/font/google";

import { TRPCReactProvider } from "src/trpc/react";
import NavBar from "./_components/navbar";
import Footer from "./_components/footer";
import CustomSeparator from "./_components/breadcrumb-trail";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const mainFont = Montserrat({
  subsets: ["latin"],
  weight: "400",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${mainFont.className } `} >
      <meta name="viewport"/>
      <body className="bg-[#F6F6F6] m-0 p-0">
        <div className="flex items-center bg-white w-full sm:pl-25 m-0 p-0 h-20">
          <div className="w-full "> 
            <NavBar/>
          </div>
        </div> 
         <div className="my-5 sm:mx-28 mx-5">
            <CustomSeparator></CustomSeparator>
        </div>

        {
        <TRPCReactProvider>{children}</TRPCReactProvider>
        }

        <footer className="bg-[#262626] mt-5">
          <Footer>hello</Footer>
        </footer> 
      </body>
    </html>
  );
}
