import "src/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import {Montserrat} from "next/font/google";

import { TRPCReactProvider } from "src/trpc/react";
import NavBar from "./_components/navbar";
import Footer from "./_components/footer";
import CustomSeparator from "./_components/breadcrumb-trail";
import IconHeader from "./_components/icon+header";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const mainFont = Montserrat({
  subsets: ["latin"],
  weight: "400",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${mainFont.className } `} >
      <meta name="viewport"/>
      <body className="bg-[#F6F6F6] m-0 p-0">
        <div className=" flex items-center bg-white w-full sm:pl-40 m-0 py-2 sm:py-0 sm:h-20">
          <div className="w-full"> 
            <NavBar/>
          </div>
        </div> 
         <div className="my-2 sm:mx-42 sm:my-5 mx-5 flex justify-between">
            <CustomSeparator></CustomSeparator>
            <div className="flex flex-wrap gap-1 md:gap-4 items-center text-gray-400">
              <p className="text-[6px] md:text-lg md:font-semibold">Next Training:</p>
              <IconHeader path={"/assets/icons/calendar.svg"} override= { " h-1 w-3 md:h-5 md:w-10"} headerfont="text-[6px] md:text-lg  text-[#74AF28]">    15 April 2024    Rolec R&D, Nottingham</IconHeader>
            </div>
        </div>

        {
        <TRPCReactProvider>{children}</TRPCReactProvider>
        }

        <footer className="bg-[#262626] mt-5">
          <Footer>hello</Footer>
        </footer> 
      </body>
    </html>
  );
}
